config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
    root to: 'pages#index'
    
    resources :publishers
    resources :authors
    resources :books
    resources :users
    resources :reviewerships, :only => [:index]
    resources :book_reviews, :only => [:index]
    resources :donations, :only => [:index, :create]
    
    post 'books/:id/post_review' => 'books#post_review'
    delete 'books/delete_review/:id' => 'books#delete_review'
    post 'users/req/:id' => 'users#req'
    
    post 'users/accept/:id', to: 'users#accept', as: 'accept'
    get 'users/reject/:id', to: 'users#reject', as: 'reject'
    
    post 'users/:id/post_review' => 'users#post_review'
    delete 'users/delete_review/:id' => 'users#delete_review'
    
    post 'reviewerships/approve/' => 'reviewerships#approve'
    post 'book_reviews/approve/' => 'book_reviews#approve'
    post '/users/donations' => 'donations#create'
    post 'donations/accept/' => 'donations#accept'
    
    get '/secret', to: 'pages#secret', as: :secret
    
    get '/queries' => 'queries#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
    has_and_belongs_to_many :books
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:show, :edit, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :biography)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :biography %><br>
    <%= f.text_area :biography %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>AuthorID</th>
      <th>Books authored</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name%></td>
          <td><%= author.author_id %></td>
          <% author.books.find_each do |book| %>
            <td><%= link_to book.title, book %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Biography:</strong>
  <%= @author.biography %>
</p>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>