config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
    root to: 'pages#index'
    
    resources :publishers
    resources :authors
    resources :books
    resources :users
    resources :reviewerships, :only => [:index]
    resources :book_reviews, :only => [:index]
    resources :donations, :only => [:index, :create]
    
    post 'books/:id/post_review' => 'books#post_review'
    delete 'books/delete_review/:id' => 'books#delete_review'
    post 'users/req/:id' => 'users#req'
    
    post 'users/accept/:id', to: 'users#accept', as: 'accept'
    get 'users/reject/:id', to: 'users#reject', as: 'reject'
    
    post 'users/:id/post_review' => 'users#post_review'
    delete 'users/delete_review/:id' => 'users#delete_review'
    
    post 'reviewerships/approve/' => 'reviewerships#approve'
    post 'book_reviews/approve/' => 'book_reviews#approve'
    post '/users/donations' => 'donations#create'
    post 'donations/accept/' => 'donations#accept'
    
    get '/secret', to: 'pages#secret', as: :secret
    
    get '/queries' => 'queries#index'

end

app/models/user.rb
class User < ActiveRecord::Base
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable    
    devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable,
    :confirmable, :lockable
       
    mount_uploader :image, ImageUploader
    validates_processing_of :image
    validate :image_size_validation
    
    validates_presence_of :name, :birth_date
    
    has_one :privilege
    
    has_many :books
    has_many :book_reviews
    
    has_many :notifications
    
    has_many :donations
    has_one :location
    
    has_many :reviewerships
    has_many :reviewers, :through => :reviewerships
    
    has_many :inverse_reviewerships, :class_name => "Reviewership", :foreign_key => 'reviewer_id'
    has_many :inverse_reviewers, :through => :inverse_reviewerships, :source => :user
    
    def send_devise_notification(notification, *args)
        devise_mailer.send(notification, self, *args).deliver_later
    end
    
    private
        def image_size_validation
            errors[:image] << "should be less than 500KB" if image.size > 0.5.megabytes
        end
end

app/models/user_type.rb
class UserType < ActiveRecord::Base
  belongs_to :user
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_user, only: [:show, :edit, :update, :destroy, :post_review, :delete_review]
  before_action :authorize_admin, only: [:index]
    
  helper_method :find_by_isbn

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
      @deal_exists = (Deal.exists?(buyer_id: current_user.id, seller_id: @user.id, confirmed: true) or Deal.exists?(buyer_id: @user.id, seller_id: current_user.id, confirmed: true))
      users = User.where(:id => @user.id)
      @hash = Gmaps4rails.build_markers(users) do |user, marker|
          if user.location              
              marker.lat user.location.latitude
              marker.lng user.location.longitude
              marker.picture ({
                  :url => view_context.image_path('marker.png'),
                  :width => 32,
                  :height => 32
                  })
          end
      end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    loc_params = {}
    loc_params[:address] = params[:user][:location]
    loc_params[:user_id] = current_user.id  
    if Location.exists?(user_id: current_user.id)
        Location.where(user_id: current_user.id)[0].update(loc_params)
    else
        Location.create!(loc_params)
    end
      
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
    
  def req
      @seller = Book.find(params[:id]).user_id
      deal_params = {}         
      deal_params[:book_id] = params[:id]
      deal_params[:seller_id] = @seller
      deal_params[:buyer_id] = current_user.id
      deal_params[:confirmed] = false
      @deal = Deal.new(deal_params)
      @deal.save
      
      noti_params = {}
      noti_params[:user_id] = @seller
      noti_params[:deal_id] = @deal.id
      @noti = Notification.new(noti_params)
      respond_to do |format|
          if @noti.save
              format.html { redirect_to :back, notice: 'Request sent!' }
          else
              format.html { redirect_to :back, notice: 'Error while sending request.' }
          end
      end
  end
    
  def accept
      deal = Deal.find(params[:id])
      respond_to do |format|
          deal.update(confirmed: true, date_of_transaction: Time.now)
          Notification.find_by(deal_id: deal.id).destroy!
          noti_params = {}
          noti_params[:user_id] = deal.buyer_id
          noti_params[:deal_id] = deal.id
          @noti = Notification.new(noti_params)
          @noti.save!
          @book = Book.find(deal.book_id)
          @book.availability = false
          @book.save!
          format.html { redirect_to :back, notice: 'Your contact information has been transferred to the user!' }
      end
  end
    
  def reject
      deal = Deal.find(params[:id])
      respond_to do |format|
          deal.destroy!
          Notification.find_by(deal_id: deal.id).destroy!
          format.html { redirect_to :back, notice: 'You have declined the request!' }
      end
  end
    
  def post_review
      @reviewership = @user.reviewerships.build(:reviewer_id => current_user.id, :review => params[:review], :rating => params[:rating],:approved => false)
      respond_to do |format|
          if @reviewership.save  
              format.html { redirect_to :back, notice: 'Your review has been queued up for admin moderation. It will be posted as soon as it is approved.' }
          end
      end
  end
    
  def delete_review
      @reviewership = current_user.inverse_reviewerships.find(params[:id])
      @reviewership.destroy
      respond_to do |format|  
          format.html { redirect_to :back, notice: 'Your review successfully deleted.' }
      end
  end
    
  def find_by_isbn isbn
      ISBN.find_by_isbn isbn
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
      @user_books = @user.books.paginate(:page => params[:page], :per_page => 3)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:user).permit(:name, :password, :birth_date, :about_me, :address, :image, :remove_image)
    end
    
    def authorize_admin
        if current_user and current_user.privilege and current_user.privilege.admin
                
        else
            respond_to do |format|
                format.html { redirect_to root_path, notice: 'Sorry, you need administrator privileges to perform that action' }
            end
        end
    end   
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_book.html.erb
<% @user_books.each do |book|%>
<div class="row">
    <div class="col-sm-12">
        <div class="well">
              <strong>Title:</strong>
              <%= link_to book.title, book_path(book)%><br/>
              <strong>ISBN:</strong>
              <%= book.isbn %><br/>             
              <strong>Authors:</strong>
              <% if book.authors %>
                <% book.authors.each do |author| %>
                  <%= author.name + " | " %>
                <% end %><br/>
              <% end %>
              <strong>Subject:</strong>
              <%= book.genre %><br/> 
              <% if book.condition %>
                <strong>Condition:</strong>
                <%= book.condition %><br/>
              <% end %>
              <% if book.market_price %>
                <strong>Market Price:</strong>
                <%= book.market_price %><br/>
              <% end %>
              <strong>Publisher:</strong>
              <td><% if book.publisher %><%= book.publisher.name %><% end %></td><br/>
              <% if book.availability %>
                <h3>Available now!</h3>
              <% else %>
                <h3>Not available.</h3>
              <% end %></br>
              <% if Donation.exists?(book_id: book.id, accepted: true) %>
                <h4>This book has been donated by the user.</h4>
              <% end %>
              <% if @user.id == current_user.id %>
              <td>Want to <%= link_to 'edit', edit_book_path(book) %> something?</td>
              <td>(Click here to <%= link_to 'delete', book, method: :delete, data: { confirm: 'Are you sure?' } %> this item)</td>              
            <% end %>
            <% deal = Deal.find_by(:book_id=>book.id) %>            
            <% if deal.present? %>
                <% if deal.buyer_id == current_user.id %>
                    <% other_end_of_deal = User.find(deal.seller_id) %>
                <% else %>
                    <% other_end_of_deal = User.find(deal.buyer_id) %>
                <% end %>
                <% if book.user != current_user %>
                    <% if deal.confirmed %>            
                        <div class="well">
                            <strong>You had a deal recently. Would you like to leave a review for the <%= link_to 'user', user_path(other_end_of_deal)%>?</strong>
                        </div>                
                    <% else %>
                        <div class="well">
                            <strong>Contact info requested! Please wait for response.</strong>
                        </div>
                    <% end %>
                <% else %>
                    <% if deal.confirmed %>            
                        <div class="well">                            
                            <strong>You had a deal recently. Would you like to leave a review for the <%= link_to 'user', user_path(other_end_of_deal)%>?</strong>
                        </div>                
                    <% else %>
                        <div class="well">
                            <strong>You have a pending contact request. Please respond!</strong>
                        </div>
                    <% end %>
                <% end %>
            <% elsif book.user != current_user %>
                <%= button_to 'Request this book', "req/#{book.id}", :method => :post, 'class' => 'btn btn-success', 'role' => 'button' %>
            <% end %>
        </div>
    </div>
</div>
<br/>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label :location %>
      <% if Location.exists?(user_id: current_user.id) %>
      <%= f.text_field :location, :size=>'50', :maxlength=>'254', class: 'form-control', :value=> current_user.location.address %>
      <% else %>
      <%= f.text_field :location, :size=>'50', placeholder: "Provide an approximate location, not full address.", :maxlength=>'254', class: 'form-control'%>
      <% end %>
  </div>

  <div class="actions">
      <%= f.submit 'Update Location', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form' %>

<%= link_to 'Back', user_path(@user) %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birth date</th>
      <th>About me</th>
      <th>Last signed in at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>       
        <td><%= user.email %></td>        
        <td><%= user.birth_date %></td>
        <td><%= user.about_me %></td>
        <td><%= user.last_sign_in_at.localtime %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div id="bookModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Add a book</h4>
            </div>
            <div class="modal-body">
                <%= form_tag books_path, method: 'post', :class => "form-horizontal", :role => "form" do %>
                <div class="form-group">
                    <label for="isbn" class="col-sm-3 control-label">Enter ISBN: </label> 
                    <div class="col-sm-7"><%= text_field :book, :isbn, class: 'form-control' %></div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-5">
                        <%= button_tag "Add book", :type=>'submit', :class => "btn btn-primary" %>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div id="donateModal" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Donate a book</h4>
            </div>
            <div class="modal-body">
                <%= form_tag url_for(:controller => 'donations', :action => 'create'), method: 'post', :class => "form-horizontal", :role => "form" do %>
                <div class="form-group">
                    <label for="isbn" class="col-sm-3 control-label">Enter Book ISBN: </label>
                    <div class="col-sm-7"><%= text_field :book, :isbn, class: 'form-control' %></div>                            
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-5">
                        <%= button_tag "Donate", :type=>'submit', :class => "btn btn-primary" %>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                    </div>
                </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

<div class="container text-center">    
  <div class="row">
    <div class="col-sm-3 well">
      <div class="well">
          <%= image_tag @user.image_url.to_s, size: "200x200", alt: "Profile Photo", class: "img-circle" %>
          <%= form_for @user, html: { multipart: true } do |f| %>
              <% if @user.errors.any? %>
                  <div id="error_explanation">
                      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
                      <ul>
                          <% @user.errors.full_messages.each do |message| %>
                          <li><%= message %></li>
                          <% end %>
                      </ul>
                  </div>
              <% end %>
              <% if @user.id == current_user.id %>
                  <div class="field">
                      <%= f.label :select_profile_photo, class: 'btn btn-primary', for: 'user_image' %><br>
                      <%= f.file_field :image, style: 'display:none' %>
                      <% if f.object.image? %>
                          <%= f.label :remove_image%>
                          <%= f.check_box :remove_image %> 
                      <% end %>
                  </div>
                  <div class="actions">
                      <%= f.submit 'Upload!', class: 'btn btn-success' %>
                  </div>
              <% end %>
          <% end %>
    </div>
    <div class="well">
          <p>
              <strong>Name:</strong>
              <%= @user.name %>
          </p>
          <% if @user.id == current_user.id %>
          <p>
              <div class="col-sm-12" style="word-wrap: break-word">
                  <strong>Email:</strong>
                  <%= @user.email %>
              </div>             
          </p>
          <% end %>          
          <p>
              <strong>Birth date:</strong>
              <%= @user.birth_date %>
          </p>
          <p>
              <div class="col-sm-12" style="word-wrap: break-word">
                  <strong>About me:</strong>
                  <%= @user.about_me %>
              </div>
          </p>
          <p>
              <strong>Last signed in at:</strong>
              <%= @user.last_sign_in_at.localtime %>
          </p>
      </div>
      <div class="well">
          <strong>Average rating for this user: </strong>
          <h1><%= number_with_precision @user.reviewerships.where(approved: true).average(:rating), precision: 1 %></h1> 
      </div>
      <% if @deal_exists %>
          <div class="well">  
              <%= form_for(@user, url: {:action => "post_review"}, method: :post) do |f| %>
              <% if @user.errors.any? %>
                    <div id="error_explanation">
                        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this review from being saved:
                        </h2>
                        <ul>
                            <% @user.errors.full_messages.each do |message| %>
                                <li><%= message %></li>
                            <% end %>
                        </ul>
                    </div>
              <% end %>
              <strong>Looks like you had a deal recently.</strong>
              <strong>Would you like to leave a review?</strong>
              <div class="field">
                  <label class="radio-inline">
                      <%= radio_button_tag(:rating, "1") %>1
                  </label>
                  <label class="radio-inline">
                      <%= radio_button_tag(:rating, "2") %>2
                  </label>
                  <label class="radio-inline">
                      <%= radio_button_tag(:rating, "3") %>3
                  </label>
                  <label class="radio-inline">
                      <%= radio_button_tag(:rating, "4") %>4
                  </label>  
                  <label class="radio-inline">
                      <%= radio_button_tag(:rating, "5") %>5
                  </label>
              </div>
              <div class="field">
                  <%= text_area_tag :review, nil,  class: 'form-control' %>
              </div>              
              <div class="actions">
                  <%= f.submit "Submit!", :class=>'btn btn-small btn-success' %>
              </div>
              <% end %>
          </div>
      <% end %>
      <div class="well">
          <h4>Reviews for user:</h4>
          <% for reviewership in @user.reviewerships %>
              <% if reviewership.approved == true %>
                <strong><%= link_to User.find(reviewership.reviewer_id).name, user_path(User.find(reviewership.reviewer_id)) %>: </strong> <br/> 
                <strong><%= reviewership.review %></strong> <br/> 
                <strong>Rated: <%= reviewership.rating %></strong> <br/>
                <strong><%= reviewership.updated_at %></strong> <br/> 
                <hr>
             <% end %>
          <% end %>
      </div>
    </div>
    <div class="col-sm-7">    
      <div class="row">
        <div class="col-sm-12">
          <div class="panel panel-default text-left">
            <div class="panel-body">
                <% if @user.id == current_user.id %>
                <h4><span class="glyphicon glyphicon-globe"></span><%= link_to 'Edit location', edit_user_path(@user) %></h4><br/>
                <% end %>
                <div style='width: inherit; height: 400px;'>
                    <div id="map" style='width: 100%; height: 100%'></div>
                </div>
            </div>
          </div>
        </div>
     </div>
    <h4>My list of books:</h4> 
        
     <%= render 'book' %>      
      
      <% if @user.id == current_user.id %>
          <div class="row">
            <div class="col-sm-12">
                <%= button_tag 'Add a new book', {'class' => 'btn btn-success btn-block', 'role' => 'button', 'data-toggle' =>  "modal", 'data-target' => '#bookModal'}  %>
            </div>
          </div>
      <% end %>
    </div>
    <div class="col-sm-2 well">
        <div class="thumbnail">
            <%= button_tag 'Donate to us!', {'class' => 'btn btn-small btn-info', 'role' => 'button', 'data-toggle' =>  "modal", 'data-target' => '#donateModal'}  %>
            <img src="" alt="" width="400" height="300">
        </div>
        <div class="well">
            <p><strong>Our most recent donor: </strong></p>
            <% donator = Donation.where(:accepted=>true).last %>
            <% if donator %>
                <%= link_to Donation.where(:accepted=>true).last.user.name, Donation.last.user %>
            <% else %>
            Sorry, no donors yet :(
            <% end %>
        </div>
    </div>
  </div>

<%= will_paginate @user_books %>
</div>

<footer class="container-fluid text-center">
</footer>

<script type="text/javascript">
    handler = Gmaps.build('Google');        
    handler.buildMap({ internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%= raw @hash.to_json %>);        
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>