config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
    root to: 'pages#index'
    
    resources :publishers
    resources :authors
    resources :books
    resources :users
    resources :reviewerships, :only => [:index]
    resources :book_reviews, :only => [:index]
    resources :donations, :only => [:index, :create]
    
    post 'books/:id/post_review' => 'books#post_review'
    delete 'books/delete_review/:id' => 'books#delete_review'
    post 'users/req/:id' => 'users#req'
    
    post 'users/accept/:id', to: 'users#accept', as: 'accept'
    get 'users/reject/:id', to: 'users#reject', as: 'reject'
    
    post 'users/:id/post_review' => 'users#post_review'
    delete 'users/delete_review/:id' => 'users#delete_review'
    
    post 'reviewerships/approve/' => 'reviewerships#approve'
    post 'book_reviews/approve/' => 'book_reviews#approve'
    post '/users/donations' => 'donations#create'
    post 'donations/accept/' => 'donations#accept'
    
    get '/secret', to: 'pages#secret', as: :secret
    
    get '/queries' => 'queries#index'

end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
    #Contact Information
    has_many :websites, :as => :contactable, :class_name => "Website"
    has_many :emails, :as => :contactable, :class_name => "Email"
    has_many :phone_numbers, :as => :contactable, :class_name => "PhoneNumber"
    has_many :addresses, :as => :contactable, :class_name => "Address"
    
    has_many :books
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :set_publisher, only: [:show, :edit, :update, :destroy]
  before_action :authorize_admin, only: [:show, :edit, :destroy]

  # GET /publishers
  # GET /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1
  # GET /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers
  # POST /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to @publisher, notice: 'Publisher was successfully created.' }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1
  # PATCH/PUT /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to @publisher, notice: 'Publisher was successfully updated.' }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1
  # DELETE /publishers/1.json
  def destroy
    @publisher.destroy
    respond_to do |format|
      format.html { redirect_to publishers_url, notice: 'Publisher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def publisher_params
      params.require(:publisher).permit(:name, :information)
    end
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/publishers/_form.html.erb
<%= form_for(@publisher) do |f| %>
  <% if @publisher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
      <% @publisher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :information %><br>
    <%= f.text_area :information %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/publishers/edit.html.erb
<h1>Editing Publisher</h1>

<%= render 'form' %>

<%= link_to 'Show', @publisher %> |
<%= link_to 'Back', publishers_path %>

app/views/publishers/index.html.erb
<h1>Listing Publishers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>PublisherID</th>
      <th>Books published</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @publishers.each do |publisher| %>
      <tr>
          <td><%= publisher.name %></td>
          <td><%= publisher.publisher_id %></td>
          <% publisher.books.find_each do |book| %>
            <td><%= link_to book.title, book %></td>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/publishers/new.html.erb
<h1>New Publisher</h1>

<%= render 'form' %>

<%= link_to 'Back', publishers_path %>

app/views/publishers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @publisher.name %>
</p>

<p>
  <strong>Information:</strong>
  <%= @publisher.information %>
</p>

<%= link_to 'Edit', edit_publisher_path(@publisher) %> |
<%= link_to 'Back', publishers_path %>