config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }
    root to: 'pages#index'
    
    resources :publishers
    resources :authors
    resources :books
    resources :users
    resources :reviewerships, :only => [:index]
    resources :book_reviews, :only => [:index]
    resources :donations, :only => [:index, :create]
    
    post 'books/:id/post_review' => 'books#post_review'
    delete 'books/delete_review/:id' => 'books#delete_review'
    post 'users/req/:id' => 'users#req'
    
    post 'users/accept/:id', to: 'users#accept', as: 'accept'
    get 'users/reject/:id', to: 'users#reject', as: 'reject'
    
    post 'users/:id/post_review' => 'users#post_review'
    delete 'users/delete_review/:id' => 'users#delete_review'
    
    post 'reviewerships/approve/' => 'reviewerships#approve'
    post 'book_reviews/approve/' => 'book_reviews#approve'
    post '/users/donations' => 'donations#create'
    post 'donations/accept/' => 'donations#accept'
    
    get '/secret', to: 'pages#secret', as: :secret
    
    get '/queries' => 'queries#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script> 
<script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <%= link_to 'OurBookShop', root_path, class: 'navbar-brand' %>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <% if user_signed_in? %>
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      Notifications <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu noti" role="menu">
                      <% current_user.notifications.each do |noti| %>
                          <% if noti.deal.confirmed %>
                            <li><%= link_to noti.deal.seller.name, user_path(noti.deal.seller) %> has agreed to share contact details with you on your request of <%= link_to noti.deal.book.title, book_path(noti.deal.book) %>. Email: <%= noti.deal.seller.email %></li>
                          <% else %>
                            <li><%= link_to noti.deal.buyer.name, user_path(noti.deal.buyer) %> has requested your book <%= link_to noti.deal.book.title, book_path(noti.deal.book) %>. Send contact details? 
                                <div class="form-inline">
                                    <div class="form-group">
                                        <%= button_to 'Yes', accept_url(noti.deal.id), :method => :post, 'class' => 'btn btn-small btn-primary', 'role' => 'button'%>   
                                    </div>
                                    <div class="form-group">
                                        <%= button_to 'No', reject_url(noti.deal.id), :method => :get, 'class' => 'btn btn-small btn-info', 'role' => 'button' %>
                                    </div>
                                 </div>
                              </li>
                           <% end %>
                            <hr>
                        <% end %>
                     </ul>
                 </li>
              <% end %>
          </ul>
          <%= form_tag books_path, :method => :get, :class => "navbar-form navbar-right" do %>
            <div class="form-group input-group">
                <%= text_field_tag(:search, params[:search], :class => "form-control", :placeholder => "Search..") %>
                <%= submit_tag "Search", :name => nil, :style => "visibility: hidden;" %>
            </div>
          <% end %>
          <ul class="nav navbar-nav navbar-right">
              <% if user_signed_in? %>
              <li class="dropdown">
                  <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <span class="glyphicon glyphicon-user"></span><%= " " +current_user.name %>
                      <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                      <li><%= link_to 'Profile', user_path(current_user.id) %></li>
                      <% if current_user and current_user.privilege and current_user.privilege.admin %>
                      <li><%= link_to 'User Reviews', reviewerships_path %></li>
                      <li><%= link_to 'Book Reviews', book_reviews_path %></li>
                      <li><%= link_to 'Donations', donations_path %></li>
                      <% end %>
                      <li><%= link_to 'Settings', edit_user_registration_path %></li>
                      <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
                  </ul>
              </li>
              <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
              <li><%= link_to 'Sign Up', new_user_registration_path %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
        <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
            <%= value %>
        </div>
        <% end %>
    </div>

    <%= yield :top_content %>

    <div class="container">
        <h1><%= yield :header %></h1>
        <%= yield %>
    </div>
</body>    
</html>